owner: keywordnew
repo: tallinn-watchtower
user-agent: keywordnew

sites:
  - name: Tallinna Vesi
    url: https://tallinnavesi.ee/
    method: GET
    icon: https://nilspace.xyz/content/images/2023/05/water.png
  - name: Elektrilevi OÜ
    url: https://www.elektrilevi.ee/en/avaleht
    method: GET
    icon: https://nilspace.xyz/content/images/2023/05/power-1.png
  - name: Elisa Eesti AS
    url: https://www.elisa.ee/
    method: GET
    icon: https://nilspace.xyz/content/images/2023/05/communication.png
  - name: Põhja-Eesti Regionaalhaigla
    url: https://www.regionaalhaigla.ee/
    method: GET
    icon: https://nilspace.xyz/content/images/2023/05/hospital.png
  - name: Politsei- ja Piirivalveamet
    url: https://www.politsei.ee/
    method: GET
    icon: https://nilspace.xyz/content/images/2023/05/emergency.png
  - name: Tallinna Linnatranspordi AS
    url: https://www.tlt.ee/
    method: GET
    icon: https://nilspace.xyz/content/images/2023/05/transportation-1.png
  - name: Monese
    url: https://www.monese.com
    method: GET
    icon: https://nilspace.xyz/content/images/2023/05/payment.png


status-website:
  baseUrl: /tallinn-watchtower
  name: 'Neighbourhood Cyber'
  logoUrl: https://nilspace.xyz/content/images/2023/05/favicon.png
  favicon: https://nilspace.xyz/content/images/2023/05/favicon.png
  introTitle: 'Tallinn 🇪🇪 watchtower'
  introMessage: 'check if critical infrastructure may be down, or use GitHub ↗️ to "Watch" and get notified'
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Neighbourhoods
      href: https://github.com/$OWNER?tab=repositories&q=watchtower
      
i18n:
  footer: This Watchtower is part of [Project Watchtower](https://nilspace.xyz/project-watchtower/).
